<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Plutus.Domain\Plutus.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MAB.DotIgnore" Version="3.0.2" />
      <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="10.0.12" />
    </ItemGroup>

</Project>
